### ISSUE TITLE
MagmaHackers second activity

### ISSUE THREAD

**Issue by ulisesac4** [diegosaul402/primera-semana#1]
Hi Diego!, let me go into details of my review:

About design: Everything is perfect in a 99.9% percent color, animations, images and information. The only thing that I would fix is the vertical padding of your footer. 

About code: There are not bad things, the code is clean and you have managed well your resources.

It is a really good page, congratulations.

**Comment by diegosaul402** [comment]
Thank you, I fix the footer as you suggest.
