### ISSUE TITLE
Maybe More Color.

### ISSUE THREAD

**Issue by SashQuasher** [diegosaul402/primera-semana#10]
Loved your design, it's simple but very classy. The only two "Issues" I could fine is that you may use a little more color, maybe just a background color? and your footer use a little more polish.

Great Work in general. Keep it that way. 👍

**Comment by diegosaul402** [comment]
Hi Emmanuel,
Yeah, I'm bad with colors, usually my color pick are very "rancheros" and ugly, so I pick gray. I've improved my footer, I hope looks better now. Thank you for your feedback.
