### ISSUE TITLE
MagmaHackers Second Activity (meaningful names)

### ISSUE THREAD

**Issue by tzohpilotl** [diegosaul402/primera-semana#2]
Hi, Diego, your page is cool and really goes with your personality. My one suggestion is that you should use meaningful names for clases. I noticed that `.page-header` is somewhat confusing because I expected it to be a class to style, well, headers, but it turned out that it wraps entire sections just to give them a margin. I believe this can be corrected to express what the class does without the need of looking at the actual code. Have a nice day!

**Comment by diegosaul402** [comment]
Hi Gil,
Well, the class name came from bootstrap and I miss used. Thank you for your feedback.
