### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by JulioC3094** [diegosaul402/primera-semana#3]
Hello Diego.
Good job!  You use a great work coding this page, the only recommendation is use more combinations of  colors in the boxes o in words. On the Internet there are many pages that have combinations of colors that you can use.

**Comment by diegosaul402** [comment]
Hi Julio,
Yes, I'm bad choosing colors, that's why I used gray xD. I'll try to choose good color for the next time. Thank you for your feedback.
