### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by aldompe95** [diegosaul402/primera-semana#7]
I like your webpage its simple and clean, the only thing i notice is that in your css you use a class name `.well` but you should use more specific class names, but dont worry it happens to me too, sometimes its a little confusing when you try to create the proper class name.
And the second thing is that you could configure the tabs of your editor with 2 tabs instead of 4, its more clean, at least that say a lot of development standards to have a clean code.
anyway good work

**Comment by diegosaul402** [comment]
Hi Aldo,
About `.well`, that name was given by bootstrap and I agree, can't tell by the name what that class do.
Is new for me what do you say about tabulation, i did not knew it, I'll read more about it, thanks!
