### ISSUE TITLE
Clean and Cool

### ISSUE THREAD

**Issue by salvadorJimenez** [diegosaul402/primera-semana#8]
The page is really cool, is clean and minimalist, maybe the conbination of colors is not the best but i dont have to much to say becouse like you said, is your first webpage and it's a good job. As you mention, Bootstrap help you a lot in the part of  responsive design. Like other guy told you, the only thing that i see is that footer is too simple, maybe you can do it better if you  add some pading or margin to the elements and maybe another font and color. Anyway good job.

**Comment by diegosaul402** [comment]
Hi Savador,
I've improved the footer, I hope it looks better now! Thank you for your feedback.
